"""Compile slimtest extension records into dbt-standard `unit_tests` YAML.

End-to-end flow per design.md §8.1:

  1. Load `slimtest.yml` (defaults if absent).
  2. Build a `FactoryRegistry` from the factories_path.
  3. Walk `models/**/*.yml` and collect every `meta.slimtest.unit_tests`
     entry, paired with its source line.
  4. For each entry, expand factory refs into literal rows.
  5. Group by model, write `target/slimtest/<model>.generated.yml`.
  6. Emit `target/slimtest/source_map.json` mapping generated test names
     back to source (file, line).

Upstream `ref()` vs `source()` disambiguation happens via the dbt
manifest. If a manifest is supplied (or auto-loaded from
`target/manifest.json`), each upstream identifier is rendered as the
right form; if not, everything falls back to `ref('<name>')` and the
caller is on the hook for any source-shaped tests it tries to run.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from io import StringIO
from pathlib import Path
from typing import Any

from ruamel.yaml import YAML

from .config import load_config
from .dbt_project import check_generated_path_in_model_paths, load_dbt_project
from .expand import ExpandedUnitTest, expand_unit_test
from .factory import FactoryRegistry, SlimTestError
from .manifest import Manifest, UpstreamRef, try_load_manifest
from .model_parser import ParsedUnitTest, find_slimtest_tests
from .parametrize import expand_parametrize
from .scenario import apply_scenario
from .schema import SlimTestConfig
from .selector import filter_tests

GENERATED_FILE_SUFFIX = ".generated.yml"
SOURCE_MAP_FILENAME = "source_map.json"
GENERATED_HEADER = "# Generated by slimtest. DO NOT EDIT.\n"


@dataclass(frozen=True)
class CompileResult:
    """Summary of a `compile_project` run.

    `source_map` is the in-memory form of what was written to
    `source_map_path`; downstream stages (notably the unittest runner)
    re-use it without round-tripping through JSON.

    `warnings` collects situations that likely need user action (e.g.
    a missing `model-paths` entry in dbt_project.yml). `notices` are
    informational reports of automatic behaviour that worked as
    designed (e.g. an upstream row that was auto-injected). CLI shows
    warnings by default and notices only under `--verbose`.
    """

    project_root: Path
    config: SlimTestConfig
    output_dir: Path
    generated_files: list[Path]
    source_map_path: Path
    source_map: dict[str, dict[str, Any]]
    test_names: list[str]
    warnings: list[str]
    notices: list[str]

    @property
    def test_count(self) -> int:
        return len(self.test_names)


class DuplicateTestNameError(SlimTestError):
    """Two unit tests resolved to the same `slimtest__<model>__<name>`."""

    def __init__(self, name: str, first: Path, second: Path) -> None:
        super().__init__(
            f"duplicate generated test name {name!r}: defined in {first} and {second}"
        )
        self.name = name


def compile_project(
    project_root: Path,
    *,
    manifest: Manifest | None = None,
    select: str | None = None,
) -> CompileResult:
    """Run the full compile flow against `project_root`.

    If `manifest` is None, we try to load `target/manifest.json`; if
    that file is also absent, upstreams are emitted as bare `ref()`
    calls. `select` accepts a dbt-style selector (see `selector.py`).
    """
    project_root = project_root.resolve()
    config = load_config(project_root)
    registry = FactoryRegistry.load(project_root / config.factories_path)

    warnings: list[str] = []
    notices: list[str] = []

    skipped_ymls: list[Path] = []
    parsed_tests = filter_tests(
        find_slimtest_tests(project_root, skipped_files=skipped_ymls), select
    )
    if skipped_ymls:
        warnings.append(
            f"skipped {len(skipped_ymls)} model yml file(s) that failed to parse "
            "but declare no slimtest tests (e.g. trailing tabs or duplicate keys "
            "dbt tolerates); run with --verbose to list them"
        )
        for skipped in skipped_ymls:
            notices.append(
                f"skipped unparseable model yml with no slimtest tests: "
                f"{_relative_or_self(skipped, project_root)}"
            )

    effective_manifest = manifest or try_load_manifest(project_root)

    expanded_by_model: dict[str, list[ExpandedUnitTest]] = {}
    seen: dict[str, Path] = {}

    for parsed in parsed_tests:
        expected_upstreams: list[str] = []
        if effective_manifest is not None:
            expected_upstreams = effective_manifest.get_upstreams(parsed.model_name)
        for resolved_spec in _resolve_spec(parsed):
            expanded = expand_unit_test(
                resolved_spec,
                model=parsed.model_name,
                registry=registry,
                source_file=parsed.source_path,
                source_line=parsed.source_line,
                expected_upstreams=expected_upstreams,
                auto_fill=config.auto_fill_upstreams,
            )
            if expanded.auto_filled_upstreams:
                for upstream in expanded.auto_filled_upstreams:
                    notices.append(
                        f"auto-injected base row of factory {upstream!r} for "
                        f"upstream {upstream!r} in test "
                        f"{expanded.prefixed_name!r} (not present in `given`)"
                    )
            if expanded.prefixed_name in seen:
                raise DuplicateTestNameError(
                    expanded.prefixed_name,
                    first=seen[expanded.prefixed_name],
                    second=parsed.source_path,
                )
            seen[expanded.prefixed_name] = parsed.source_path
            expanded_by_model.setdefault(parsed.model_name, []).append(expanded)

    dbt_project = load_dbt_project(project_root)
    if dbt_project is not None:
        warning = check_generated_path_in_model_paths(
            dbt_project, config.generated_yml_path
        )
        if warning is not None:
            warnings.append(warning)

    output_dir = project_root / config.generated_yml_path
    output_dir.mkdir(parents=True, exist_ok=True)

    generated_files: list[Path] = []
    source_map: dict[str, dict[str, Any]] = {}

    for model_name, tests in sorted(expanded_by_model.items()):
        out_path = output_dir / f"{model_name}{GENERATED_FILE_SUFFIX}"
        _write_generated_yml(out_path, tests, manifest=effective_manifest)
        generated_files.append(out_path)

        rel_out = _relative_or_self(out_path, project_root)
        for test in tests:
            source_map[test.prefixed_name] = {
                "source_file": str(test.source_file),
                "source_line": test.source_line,
                "generated_file": str(rel_out),
                "model": test.model,
                "original_name": test.original_name,
            }

    source_map_path = output_dir / SOURCE_MAP_FILENAME
    with source_map_path.open("w", encoding="utf-8") as fh:
        json.dump(source_map, fh, indent=2, sort_keys=True)
        fh.write("\n")

    test_names = sorted(source_map.keys())

    return CompileResult(
        project_root=project_root,
        config=config,
        output_dir=output_dir,
        generated_files=generated_files,
        source_map_path=source_map_path,
        source_map=source_map,
        test_names=test_names,
        warnings=warnings,
        notices=notices,
    )


# -- yml writer --------------------------------------------------------


def _write_generated_yml(
    path: Path, tests: list[ExpandedUnitTest], *, manifest: Manifest | None
) -> None:
    """Render the dbt-standard unit_tests yml for one model."""
    yaml = YAML(typ="rt")
    yaml.indent(mapping=2, sequence=4, offset=2)
    yaml.default_flow_style = False

    document = _build_document(tests, manifest=manifest)
    buf = StringIO()
    yaml.dump(document, buf)

    with path.open("w", encoding="utf-8") as fh:
        fh.write(GENERATED_HEADER)
        fh.write(buf.getvalue())


def _build_document(
    tests: list[ExpandedUnitTest], *, manifest: Manifest | None
) -> dict[str, Any]:
    """Build the plain Python dict that becomes the generated yml file."""
    return {
        "version": 2,
        "unit_tests": [_test_to_dbt_dict(t, manifest=manifest) for t in tests],
    }


def _test_to_dbt_dict(
    test: ExpandedUnitTest, *, manifest: Manifest | None
) -> dict[str, Any]:
    entry: dict[str, Any] = {
        "name": test.prefixed_name,
        "model": test.model,
    }
    if test.description:
        entry["description"] = test.description
    entry["given"] = [
        {"input": _input_expression(upstream, manifest), "rows": rows}
        for upstream, rows in test.given.items()
    ]
    entry["expect"] = {"rows": test.expect}
    return entry


def _input_expression(upstream: str, manifest: Manifest | None) -> str:
    """`ref(...)` or `source(...)` depending on what the manifest knows."""
    if manifest is None:
        return UpstreamRef(kind="ref", name=upstream).to_input_expression()
    return manifest.resolve(upstream).to_input_expression()


def _resolve_spec(parsed: ParsedUnitTest) -> list[Any]:
    """Apply `parametrize` (1-to-N) and `scenario` (merge given) to one spec.

    The output is a flat list of `UnitTestSpec`s with neither field set,
    ready to feed `expand_unit_test`.
    """
    expanded = expand_parametrize(parsed.spec)
    return [apply_scenario(spec, parsed.scenarios) for spec in expanded]


def _relative_or_self(path: Path, base: Path) -> Path:
    try:
        return path.relative_to(base)
    except ValueError:
        return path


__all__ = [
    "CompileResult",
    "DuplicateTestNameError",
    "GENERATED_FILE_SUFFIX",
    "GENERATED_HEADER",
    "SOURCE_MAP_FILENAME",
    "compile_project",
]
