"""End-to-end tests for `lighttest.compile.compile_project`."""

from __future__ import annotations

import json
import textwrap
from pathlib import Path

import pytest
from ruamel.yaml import YAML

from lighttest.compile import (
    GENERATED_FILE_SUFFIX,
    SOURCE_MAP_FILENAME,
    DuplicateTestNameError,
    compile_project,
)

# -- helpers ----------------------------------------------------------


def _write(path: Path, content: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(textwrap.dedent(content).lstrip(), encoding="utf-8")
    return path


def _load_yml(path: Path):
    return YAML(typ="safe").load(path.read_text(encoding="utf-8"))


@pytest.fixture
def project(tmp_path: Path):
    """A minimal dbt project skeleton under tmp_path.

    Each fixture-using test seeds factories and model ymls as needed.
    """
    (tmp_path / "models").mkdir()
    (tmp_path / "tests" / "lighttest_factories").mkdir(parents=True)
    return tmp_path


# -- happy path -------------------------------------------------------


def test_empty_project_compiles_to_zero_tests(project):
    result = compile_project(project)
    assert result.test_count == 0
    assert result.generated_files == []
    assert result.source_map_path.exists()
    assert json.loads(result.source_map_path.read_text()) == {}


def test_factory_backed_test_is_expanded(project):
    _write(
        project / "tests/lighttest_factories/users.yml",
        """
        factories:
          user:
            base: {id: 1, name: alice, tier: std}
            traits:
              premium: {tier: premium}
        """,
    )
    _write(
        project / "models/marts/m.yml",
        """
        version: 2
        models:
          - name: m
            meta:
              lighttest:
                unit_tests:
                  - name: test_xxx
                    given:
                      users:
                        - {factory: user, trait: premium, override: {id: 99}}
                    expect:
                      - {a: 1}
        """,
    )

    result = compile_project(project)
    assert result.test_count == 1
    assert len(result.generated_files) == 1

    generated = _load_yml(result.generated_files[0])
    assert generated["version"] == 2
    unit_tests = generated["unit_tests"]
    assert len(unit_tests) == 1
    test = unit_tests[0]
    assert test["name"] == "lighttest__m__test_xxx"
    assert test["model"] == "m"
    assert test["given"] == [
        {
            "input": "ref('users')",
            "rows": [{"id": 99, "name": "alice", "tier": "premium"}],
        }
    ]
    assert test["expect"] == {"rows": [{"a": 1}]}


def test_generated_file_path_uses_model_name(project):
    _write(
        project / "models/m.yml",
        """
        models:
          - name: my_model
            meta:
              lighttest:
                unit_tests:
                  - {name: t, given: {u: [{x: 1}]}, expect: []}
        """,
    )
    result = compile_project(project)
    expected = project / "target" / "lighttest" / f"my_model{GENERATED_FILE_SUFFIX}"
    assert result.generated_files == [expected]


def test_generated_header_is_present(project):
    _write(
        project / "models/m.yml",
        """
        models:
          - name: m
            meta:
              lighttest:
                unit_tests:
                  - {name: t, given: {u: [{x: 1}]}, expect: []}
        """,
    )
    result = compile_project(project)
    content = result.generated_files[0].read_text(encoding="utf-8")
    assert content.startswith("# Generated by lighttest.")


def test_description_is_preserved(project):
    _write(
        project / "models/m.yml",
        """
        models:
          - name: m
            meta:
              lighttest:
                unit_tests:
                  - name: t
                    description: a useful test
                    given: {u: [{x: 1}]}
                    expect: []
        """,
    )
    result = compile_project(project)
    generated = _load_yml(result.generated_files[0])
    assert generated["unit_tests"][0]["description"] == "a useful test"


def test_description_omitted_when_empty(project):
    _write(
        project / "models/m.yml",
        """
        models:
          - name: m
            meta:
              lighttest:
                unit_tests:
                  - {name: t, given: {u: [{x: 1}]}, expect: []}
        """,
    )
    result = compile_project(project)
    generated = _load_yml(result.generated_files[0])
    assert "description" not in generated["unit_tests"][0]


def test_multiple_models_produce_multiple_files(project):
    _write(
        project / "models/a.yml",
        """
        models:
          - name: a
            meta:
              lighttest:
                unit_tests:
                  - {name: t_a, given: {u: [{x: 1}]}, expect: []}
        """,
    )
    _write(
        project / "models/b.yml",
        """
        models:
          - name: b
            meta:
              lighttest:
                unit_tests:
                  - {name: t_b, given: {u: [{x: 2}]}, expect: []}
        """,
    )
    result = compile_project(project)
    names = sorted(p.name for p in result.generated_files)
    assert names == [f"a{GENERATED_FILE_SUFFIX}", f"b{GENERATED_FILE_SUFFIX}"]


# -- source map -------------------------------------------------------


def test_source_map_records_each_test(project):
    _write(
        project / "models/m.yml",
        """\
version: 2
models:
  - name: m
    meta:
      lighttest:
        unit_tests:
          - name: alpha
            given: {u: [{x: 1}]}
            expect: []
""",
    )
    result = compile_project(project)
    smap_data = json.loads(result.source_map_path.read_text())

    entry = smap_data["lighttest__m__alpha"]
    assert entry["source_file"] == "models/m.yml"
    # "- name: alpha" is line 7 (1-indexed) in the YAML above.
    assert entry["source_line"] == 7
    assert entry["model"] == "m"
    assert entry["original_name"] == "alpha"
    assert entry["generated_file"].endswith(f"m{GENERATED_FILE_SUFFIX}")


def test_source_map_filename(project):
    _write(
        project / "models/m.yml",
        """
        models:
          - name: m
            meta:
              lighttest:
                unit_tests:
                  - {name: t, given: {u: [{x: 1}]}, expect: []}
        """,
    )
    result = compile_project(project)
    assert result.source_map_path.name == SOURCE_MAP_FILENAME
    assert result.source_map_path.parent == result.output_dir


# -- duplicate detection ---------------------------------------------


def test_duplicate_prefixed_name_across_files_raises(project):
    # Both files put a `test_same` under model `m` -- when prefixed they collide.
    _write(
        project / "models/a.yml",
        """
        models:
          - name: m
            meta:
              lighttest:
                unit_tests:
                  - {name: test_same, given: {u: [{x: 1}]}, expect: []}
        """,
    )
    _write(
        project / "models/b.yml",
        """
        models:
          - name: m
            meta:
              lighttest:
                unit_tests:
                  - {name: test_same, given: {u: [{x: 2}]}, expect: []}
        """,
    )
    with pytest.raises(DuplicateTestNameError) as exc_info:
        compile_project(project)
    assert exc_info.value.name == "lighttest__m__test_same"


# -- factories integration -------------------------------------------


def test_custom_factories_path_in_config(project):
    _write(
        project / "lighttest.yml",
        """
        factories_path: my_factories
        """,
    )
    _write(
        project / "my_factories/users.yml",
        """
        factories:
          user:
            base: {id: 7}
        """,
    )
    _write(
        project / "models/m.yml",
        """
        models:
          - name: m
            meta:
              lighttest:
                unit_tests:
                  - name: t
                    given:
                      users: [{factory: user}]
                    expect: []
        """,
    )
    result = compile_project(project)
    generated = _load_yml(result.generated_files[0])
    assert generated["unit_tests"][0]["given"][0]["rows"] == [{"id": 7}]


def test_custom_generated_yml_path_in_config(project):
    _write(
        project / "lighttest.yml",
        """
        generated_yml_path: out/light
        """,
    )
    _write(
        project / "models/m.yml",
        """
        models:
          - name: m
            meta:
              lighttest:
                unit_tests:
                  - {name: t, given: {u: [{x: 1}]}, expect: []}
        """,
    )
    result = compile_project(project)
    assert result.output_dir == project / "out" / "light"
    assert result.generated_files[0].parent == project / "out" / "light"


# -- --select integration --------------------------------------------


def test_select_by_model_filters_tests(project):
    _write(
        project / "models/a.yml",
        """
        models:
          - name: a
            meta:
              lighttest:
                unit_tests:
                  - {name: t_a, given: {u: [{x: 1}]}, expect: []}
          - name: b
            meta:
              lighttest:
                unit_tests:
                  - {name: t_b, given: {u: [{x: 2}]}, expect: []}
        """,
    )
    result = compile_project(project, select="a")
    assert result.test_names == ["lighttest__a__t_a"]


def test_select_by_test_name_filters_tests(project):
    _write(
        project / "models/m.yml",
        """
        models:
          - name: m
            meta:
              lighttest:
                unit_tests:
                  - {name: alpha, given: {u: [{x: 1}]}, expect: []}
                  - {name: beta,  given: {u: [{x: 2}]}, expect: []}
        """,
    )
    result = compile_project(project, select="beta")
    assert result.test_names == ["lighttest__m__beta"]


def test_select_test_type_unit_returns_all(project):
    _write(
        project / "models/m.yml",
        """
        models:
          - name: m
            meta:
              lighttest:
                unit_tests:
                  - {name: a, given: {u: [{x: 1}]}, expect: []}
                  - {name: b, given: {u: [{x: 2}]}, expect: []}
        """,
    )
    result = compile_project(project, select="test_type:unit")
    assert len(result.test_names) == 2


# -- upstream auto-fill ----------------------------------------------


def _write_manifest_with_depends_on(project: Path, depends_on: dict[str, list[str]]):
    import json

    nodes = {}
    for model_name, deps in depends_on.items():
        nodes[f"model.proj.{model_name}"] = {
            "resource_type": "model",
            "name": model_name,
            "depends_on": {"nodes": deps},
        }
    target = project / "target"
    target.mkdir(parents=True, exist_ok=True)
    (target / "manifest.json").write_text(
        json.dumps({"nodes": nodes, "sources": {}}), encoding="utf-8"
    )


def test_auto_fill_injects_missing_upstream(project):
    _write(
        project / "tests/lighttest_factories/users.yml",
        """
        factories:
          users:
            base: {id: 1, name: alice}
        """,
    )
    _write(
        project / "models/m.yml",
        """
        models:
          - name: m
            meta:
              lighttest:
                unit_tests:
                  - name: t
                    given:
                      orders: [{x: 1}]
                    expect: []
        """,
    )
    _write_manifest_with_depends_on(
        project, {"m": ["model.proj.users", "model.proj.orders"]}
    )
    result = compile_project(project)
    assert result.test_count == 1
    # Warnings should mention the auto-fill.
    assert any("users" in w for w in result.warnings)


def test_auto_fill_disabled_via_config(project):
    _write(
        project / "lighttest.yml",
        """
        auto_fill_upstreams: false
        """,
    )
    _write(
        project / "tests/lighttest_factories/users.yml",
        """
        factories:
          users:
            base: {id: 1}
        """,
    )
    _write(
        project / "models/m.yml",
        """
        models:
          - name: m
            meta:
              lighttest:
                unit_tests:
                  - {name: t, given: {orders: [{x: 1}]}, expect: []}
        """,
    )
    _write_manifest_with_depends_on(
        project, {"m": ["model.proj.users", "model.proj.orders"]}
    )
    result = compile_project(project)
    # No warning about users, because auto-fill is disabled.
    assert not any("users" in w for w in result.warnings)


# -- dbt_project model-paths warning ---------------------------------


def test_model_paths_missing_target_lighttest_warns(project):
    (project / "dbt_project.yml").write_text(
        "name: proj\nmodel-paths: [models]\n", encoding="utf-8"
    )
    _write(
        project / "models/m.yml",
        """
        models:
          - name: m
            meta:
              lighttest:
                unit_tests:
                  - {name: t, given: {u: [{x: 1}]}, expect: []}
        """,
    )
    result = compile_project(project)
    assert any("target/lighttest" in w and "model-paths" in w for w in result.warnings)


def test_model_paths_with_target_lighttest_no_warning(project):
    (project / "dbt_project.yml").write_text(
        "name: proj\nmodel-paths: [models, target/lighttest]\n", encoding="utf-8"
    )
    _write(
        project / "models/m.yml",
        """
        models:
          - name: m
            meta:
              lighttest:
                unit_tests:
                  - {name: t, given: {u: [{x: 1}]}, expect: []}
        """,
    )
    result = compile_project(project)
    assert not any("model-paths" in w for w in result.warnings)


def test_no_warning_when_dbt_project_yml_missing(project):
    _write(
        project / "models/m.yml",
        """
        models:
          - name: m
            meta:
              lighttest:
                unit_tests:
                  - {name: t, given: {u: [{x: 1}]}, expect: []}
        """,
    )
    result = compile_project(project)
    assert not any("model-paths" in w for w in result.warnings)
