name: 'lighttest_sample'
version: '1.0.0'
config-version: 2

profile: 'lighttest_sample'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  lighttest_sample:
    intermediate:
      +materialized: view
    marts:
      +materialized: table

seeds:
  lighttest_sample:
    +quote_columns: false
